name: self-hosted-linux-checkout-test

on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  basic:
    runs-on: self-hosted
    name: linux
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        clean: true
      env:
        GIT_TRACE: true
