name: self-hosted-linux-checkout-test

on:
  workflow_dispatch:

jobs:
  basic:
    runs-on: self-hosted
    name: linux
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        clean: true
